# -*- coding: utf-8 -*-
"""The data-deletion page in ar / nl.

The in-app control names embedded here are pulled from content.json at build
time, never typed out, so the steps always name the buttons the app really
shows in that language.
"""

DD = {}

DD["ar"] = {
    "title": "حذف البيانات — زُلْفَى",
    "desc": "كيف تحذف حساب زُلْفَى وبياناتك: الأدوات داخل التطبيق، وما يُحذف، وما يُحتفظ به، وكيف تطلب الحذف بالبريد.",
    "h1": "حذف البيانات",
    "sub": "كيف تحذف حساب زُلْفَى وبياناتك",
    "updated": "آخر تحديث: ٢٧ أغسطس ٢٠٢٦",
    "summary": "يمكنك حذف كل شيء بنفسك من داخل التطبيق في نقرات قليلة — دون مراسلة أحد ودون انتظار. والحذف فوري ونهائي.",
    "toc": ["التطبيق والمطوّر", "احذف بياناتك داخل التطبيق", "اطلب الحذف بالبريد",
            "ما الذي يُحذف", "ما الذي يبقى", "بيانات محفوظة على جهازك وحده", "الحذف التلقائي"],
    "s1h": "التطبيق والمطوّر",
    "s1_app": "التطبيق:", "s1_dev": "المطوّر:", "s1_contact": "التواصل للخصوصية والدعم:",
    "s1_note": "لا يطلب زُلْفَى اسمك الحقيقي ولا بريدك الإلكتروني ولا رقم هاتفك ولا تاريخ ميلادك، وليس فيه كلمة مرور. والحساب الوحيد الذي يُنشئه حساب تقني يُستخدم لتحدّي اليوم التنافسي. والتفصيل الكامل في",
    "s1_pp": "سياسة الخصوصية",
    "s2h": "احذف بياناتك داخل التطبيق",
    "s2_intro": "هذا هو الطريق المباشر وهو ما نوصي به: لا يحتاج مراسلة أحد، ويسري فورًا.",
    "s2_openH": "افتح الأدوات",
    "s2_open": ["افتح زُلْفَى.", "اضغط زر <strong>القائمة</strong> (☰) أعلى الشاشة.",
                "اضغط <strong>%(privacy)s</strong>.", "انزل إلى أسفل الصفحة. ستجد هناك أداتَي الحذف."],
    "s2_srvH": "احذف حسابك على الخادم",
    "s2_srv": ["تحت <strong>%(delTitle)s</strong>، اضغط زر <strong>%(delAction)s</strong>.",
               "تظهر نافذة تأكيد تسرد بالضبط ما سيُحذف. اضغط <strong>%(delConfirm)s</strong>.",
               "يؤكّد التطبيق بعبارة <em>«%(delDone)s»</em>. والحذف فوري ولا يمكن التراجع عنه."],
    "s2_locH": "امسح البيانات المحفوظة على جهازك",
    "s2_loc": ["في الصفحة نفسها، تحت <strong>%(clearTitle)s</strong>، اضغط <strong>%(clearAction)s</strong>.",
               "أكّد بالضغط على <strong>%(clearConfirm)s</strong>."],
    "s2_why": "الأداتان منفصلتان عمدًا: مسح جهاز واحد يجب ألّا يُتلف حسابًا ما زال قائمًا على الخادم، وحذف الحساب يجب ألّا يمسح إعدادات هاتف ما زلت تستعمله. استخدم ما تحتاجه، أو كليهما.",
    "s2_orderT": "إن أردت إزالة كل شيء، فافعل ذلك بهذا الترتيب:",
    "s2_orderB": "احذف حساب المسابقة <em>أوّلًا</em>، ثم امسح البيانات المحلية أو أزل تثبيت التطبيق.",
    "s2_orderN": "إزالة تثبيت التطبيق، أو مسح تخزينه من إعدادات أندرويد، يزيل الجلسة التقنية التي تربط هذا الجهاز بحساب المسابقة. وإن فعلت ذلك قبل حذف الحساب، بقي الحساب على الخادم دون طريق للوصول إليه من ذلك الجهاز — وانظر بند «الحذف التلقائي» لما يحدث له بعدها.",
    "s3h": "اطلب الحذف بالبريد",
    "s3_intro": "إن تعذّر عليك استخدام الأداة داخل التطبيق — كأن يكون التطبيق مُزالًا بالفعل — فراسلنا على:",
    "s3_incl": "أرفق ما يلي:",
    "s3_li": ["<strong>اسم المستخدم في زُلْفَى</strong> — الاسم الظاهر في لوحة الشرف؛ و",
              "جملة تفيد أنك تريد حذف حساب المسابقة الخاص بك."],
    "s3_only": "هذا كل ما نحتاجه، وهو كل ما نطلبه. <strong>لا ترسل كلمات مرور ولا وثائق هوية ولا بيانات دفع ولا أي معلومات شخصية أخرى</strong> — فزُلْفَى لا حاجة له بها ولا يطلبها أبدًا.",
    "s3_limit": "وهنا حدّ نذكره بصراحة: اسم المستخدم هو <em>الشيء الوحيد</em> الذي يعرّفنا بالحساب. فإن لم تختر اسم مستخدم قط، فحسابك لا يحمل اسمًا ولا سجلّ تحدٍّ، ولا يوجد في رسالة بريد ما يدلّنا على أيّ حساب هو حسابك. في هذه الحالة استخدم الأداة داخل التطبيق، أو اترك التطبيق ببساطة — فحساب بهذه الحال يُحذف تلقائيًا كما هو موضّح أدناه.",
    "s3_act": "ونتصرّف في طلبات الحذف فور اطّلاعنا عليها.",
    "s4h": "ما الذي يُحذف",
    "s4_intro": "حذف حساب المسابقة — سواء فعلته داخل التطبيق أو طلبته منّا — يزيل نهائيًا كل ما يحفظه الخادم عنك:",
    "s4_tail": "هذه السجلّات مرتبطة بالحساب وتُزال معه في العملية نفسها. لا شيء يُؤرشف ولا يُنسخ إلى مكان آخر ولا يُترك في حالة معطّلة، ولا يمكن استرجاع شيء بعدها. وإن استخدمت المسابقة لاحقًا أُنشئ لك حساب جديد يبدأ من الصفر.",
    "s5h": "ما الذي يبقى",
    "s5_lead": "<strong>لا يبقى أي بيان مرتبط بك.</strong> ولا توجد مدة احتفاظ ببيانات المسابقة بعد الحذف، لأنّ شيئًا منها لا ينجو من الحذف.",
    "s5_two": "وللتمام، أمران لا يتأثّران، وليس في أيّهما شيء عنك:",
    "s5_li": ["<strong>بنك الأسئلة وتعريفات تحدّي اليوم.</strong> وهي محتوى التطبيق المشترك — الأسئلة نفسها وأيّ خمسة منها كانت في يوم بعينه. هي ذاتها لكل مستخدم، ولا تحمل أي إشارة إلى أي حساب، وليست بيانات شخصية.",
              "<strong>البيانات المحفوظة على جهازك وحده.</strong> حذف الحساب لا يمسّ هاتفك. انظر البند التالي."],
    "s6h": "بيانات محفوظة على جهازك وحده",
    "s6_intro": "معظم زُلْفَى لا يصل إلى أي خادم أصلًا. فمواقيت الصلاة والقرآن والأذكار والأدعية والقبلة تُحسب وتُحفظ على جهازك، وحذف حساب المسابقة يتركها كما هي. ولإزالتها أمامك خياران.",
    "s6_inapp": "<strong>داخل التطبيق</strong> — %(clearAction)s، في صفحة الخصوصية كما سبق، يحذف: موقع الصلاة وإعدادات الحساب؛ وتفضيلات الإشعارات والقبلة المباشرة؛ وتقدّم قراءة القرآن والعلامات والآيات المحفوظة والمفضلة والقارئ المختار؛ والأدعية والأذكار المحفوظة والمفضلة؛ وتقدّم الأذكار؛ وسجل القراءة؛ ولغة الواجهة؛ والنسخة المؤقتة من مقاطع التفسير التي فتحتها.",
    "s6_android": "<strong>من أندرويد</strong> — إزالة تثبيت زُلْفَى، أو مسح تخزينه من إعدادات التطبيقات في جهازك، تزيل كل ما خزّنه التطبيق، بما فيه الجلسة التقنية المذكورة في البند الثاني. وهذا هو المسح المحلي الكامل.",
    "s6_backup": "ولاحظ أن جهازك قد يحتفظ بنسخة احتياطية من بيانات التطبيق في حسابك أنت على Google إن كان النسخ الاحتياطي مفعّلًا في إعدادات أندرويد. وتلك النسخة تخصّك أنت وGoogle لا زُلْفَى، وتُدار من إعدادات النسخ الاحتياطي في جهازك.",
    "s7h": "الحذف التلقائي",
    "s7_intro": "لست مضطرًا لفعل شيء كي يختفي حساب غير مستخدم. فالحسابات تُحذف تلقائيًا بعد مدة من عدم النشاط، وأيّ نشاط جديد — مجرّد فتح زُلْفَى — يعيد المدة إلى بدايتها:",
    "s7_li": ["الحساب الذي ما زال <strong>فارغًا</strong> — بلا اسم مستخدم، وبلا محاولات أو إجابات، وبلا سجلّ توكنز، ورصيده صفر — يُحذف بعد <strong>٦٠ يومًا متتاليًا</strong> من عدم النشاط.",
              "الحساب الذي يحمل <strong>اسم مستخدم أو أي سجلّ مسابقة</strong> يُحذف بعد <strong>٣٦٥ يومًا متتاليًا</strong> من عدم النشاط."],
    "s7_same": "والحذف التلقائي يزيل البيانات نفسها المذكورة في البند الرابع، نهائيًا.",
    "s7_only": "وهاتان هما المدّتان الوحيدتان اللتان تنطبقان على بياناتك. وهما مهلتا حذف لا حدّ أدنى للاحتفاظ: يمكنك الحذف قبلهما دائمًا، ولا شيء يُلزمنا بحفظ بياناتك أي مدة.",
}

DD["nl"] = {
    "title": "Gegevens verwijderen — ZULFAA",
    "desc": "Hoe u uw ZULFAA-account en gegevens verwijdert: de knoppen in de app, wat er wordt verwijderd, wat blijft, en hoe u verwijdering per e-mail aanvraagt.",
    "h1": "Gegevens verwijderen",
    "sub": "Hoe u uw ZULFAA-account en gegevens verwijdert",
    "updated": "Laatst bijgewerkt: 27 augustus 2026",
    "summary": "U kunt alles zelf verwijderen, vanuit de app, in een paar tikken — zonder iemand te mailen en zonder wachten. Verwijderen gebeurt onmiddellijk en is definitief.",
    "toc": ["App en ontwikkelaar", "Uw gegevens verwijderen in de app", "Verwijdering aanvragen per e-mail",
            "Wat wordt verwijderd", "Wat blijft bewaard", "Gegevens die alleen op uw apparaat staan", "Automatische verwijdering"],
    "s1h": "App en ontwikkelaar",
    "s1_app": "App:", "s1_dev": "Ontwikkelaar:", "s1_contact": "Contact voor privacy en ondersteuning:",
    "s1_note": "ZULFAA vraagt nooit om uw echte naam, e-mailadres, telefoonnummer of geboortedatum, en heeft geen wachtwoord. Het enige account dat de app aanmaakt is een technisch account voor de dagelijkse uitdaging. De volledige uitleg staat in het",
    "s1_pp": "privacybeleid",
    "s2h": "Uw gegevens verwijderen in de app",
    "s2_intro": "Dit is de directe weg en de weg die wij aanraden: er hoeft niemand gemaild te worden, en het werkt onmiddellijk.",
    "s2_openH": "De knoppen openen",
    "s2_open": ["Open ZULFAA.", "Tik op de <strong>menuknop</strong> (☰) bovenaan het scherm.",
                "Tik op <strong>%(privacy)s</strong>.", "Scroll naar de onderkant van die pagina. Daar staan de twee knoppen."],
    "s2_srvH": "Uw account op de server verwijderen",
    "s2_srv": ["Tik onder <strong>%(delTitle)s</strong> op de knop <strong>%(delAction)s</strong>.",
               "Een bevestigingsvenster toont precies wat er verdwijnt. Tik op <strong>%(delConfirm)s</strong>.",
               "De app bevestigt met <em>“%(delDone)s”</em>. Het verwijderen is onmiddellijk en niet ongedaan te maken."],
    "s2_locH": "De gegevens op uw apparaat wissen",
    "s2_loc": ["Tik op dezelfde pagina, onder <strong>%(clearTitle)s</strong>, op <strong>%(clearAction)s</strong>.",
               "Bevestig met <strong>%(clearConfirm)s</strong>."],
    "s2_why": "De twee knoppen staan bewust los van elkaar: het wissen van één apparaat mag geen account vernietigen dat nog op de server bestaat, en het verwijderen van het account mag geen instellingen wissen op een telefoon die u nog gebruikt. Gebruik wat u nodig heeft, of allebei.",
    "s2_orderT": "Wilt u dat alles weg is, doe het dan in deze volgorde:",
    "s2_orderB": "verwijder <em>eerst</em> het wedstrijdaccount, wis daarna de lokale gegevens of verwijder de app.",
    "s2_orderN": "De app verwijderen, of de opslag ervan wissen via de app-instellingen van Android, verwijdert de technische sessie die dit apparaat aan uw wedstrijdaccount koppelt. Doet u dat vóór het verwijderen van het account, dan blijft het account op de server bestaan zonder dat het vanaf dat apparaat nog bereikbaar is — zie “Automatische verwijdering” voor wat er dan mee gebeurt.",
    "s3h": "Verwijdering aanvragen per e-mail",
    "s3_intro": "Kunt u de knop in de app niet gebruiken — bijvoorbeeld omdat de app al verwijderd is — schrijf dan naar:",
    "s3_incl": "Vermeld daarbij:",
    "s3_li": ["<strong>uw ZULFAA-gebruikersnaam</strong> — de naam die op de Erelijst staat; en",
              "een zin waarin u vraagt uw wedstrijdaccount te verwijderen."],
    "s3_only": "Meer hebben we niet nodig, en meer vragen we ook niet. <strong>Stuur geen wachtwoorden, identiteitsbewijzen, betaalgegevens of andere persoonsgegevens</strong> — ZULFAA heeft er niets aan en vraagt er nooit om.",
    "s3_limit": "Eén beperking, eerlijk gezegd: de gebruikersnaam is het <em>enige</em> dat een account voor ons identificeert. Heeft u nooit een gebruikersnaam gekozen, dan bevat uw account geen naam en geen wedstrijdgeschiedenis, en kan geen e-mail ons vertellen welk account het uwe is. Gebruik in dat geval de knop in de app, of laat de app gewoon los — een account in die staat wordt automatisch verwijderd, zoals hieronder beschreven.",
    "s3_act": "Wij handelen verwijderingsverzoeken af zodra we ze lezen.",
    "s4h": "Wat wordt verwijderd",
    "s4_intro": "Het verwijderen van het wedstrijdaccount — of u dat nu zelf in de app doet of ons erom vraagt — verwijdert definitief alles wat de server over u bewaart:",
    "s4_tail": "Deze gegevens horen bij het account en verdwijnen er in dezelfde handeling mee. Er wordt niets gearchiveerd, elders gekopieerd of in een uitgeschakelde staat bewaard, en niets kan daarna worden hersteld. Doet u later opnieuw mee aan de wedstrijd, dan wordt een nieuw account aangemaakt dat bij nul begint.",
    "s5h": "Wat blijft bewaard",
    "s5_lead": "<strong>Er blijven geen aan u gekoppelde gegevens bewaard.</strong> Er geldt na verwijdering geen bewaartermijn voor uw wedstrijdgegevens, omdat er niets van overblijft.",
    "s5_two": "Voor de volledigheid: twee dingen blijven ongemoeid, en geen van beide bevat iets over u:",
    "s5_li": ["<strong>De vragenbank en de definities van de dagelijkse uitdaging.</strong> Dat is de gedeelde inhoud van de app — de vragen zelf en welke vijf er op een bepaalde dag waren ingesteld. Ze zijn voor iedere gebruiker gelijk, verwijzen naar geen enkel account en zijn geen persoonsgegevens.",
              "<strong>Gegevens die alleen op uw apparaat staan.</strong> Het verwijderen van het account raakt uw telefoon niet. Zie het volgende punt."],
    "s6h": "Gegevens die alleen op uw apparaat staan",
    "s6_intro": "Het meeste van ZULFAA bereikt nooit een server. Gebedstijden, de Koran, adhkar, doe'a's en de qibla worden op uw eigen apparaat berekend en bewaard, en het verwijderen van uw wedstrijdaccount laat dat alles ongemoeid. Om het te verwijderen heeft u twee mogelijkheden.",
    "s6_inapp": "<strong>In de app</strong> — %(clearAction)s, op de privacypagina zoals hierboven beschreven, verwijdert: uw gebedslocatie en berekeningsinstellingen; uw meldings- en live-qiblavoorkeuren; uw Koran-leesvoortgang, bladwijzers, opgeslagen verzen, favorieten en gekozen reciteur; uw opgeslagen en favoriete doe'a's en adhkar; uw adhkar-voortgang; uw leesgeschiedenis; uw interfacetaal; en de kortstondige cache van tafsir-passages die u hebt geopend.",
    "s6_android": "<strong>Vanuit Android</strong> — ZULFAA verwijderen, of de opslag ervan wissen in de app-instellingen van uw toestel, verwijdert alles wat de app heeft opgeslagen, inclusief de technische sessie uit punt 2. Dit is de volledige lokale wis.",
    "s6_backup": "Let op: uw toestel kan een back-up van de appgegevens in uw eigen Google-account bewaren als back-up aanstaat in uw Android-instellingen. Die back-up is van u en van Google, niet van ZULFAA, en wordt beheerd vanuit de back-upinstellingen van uw toestel.",
    "s7h": "Automatische verwijdering",
    "s7_intro": "U hoeft niets te doen om een ongebruikt account te laten verdwijnen. Accounts worden automatisch verwijderd na een periode zonder activiteit, en elke nieuwe activiteit — alleen al het openen van ZULFAA — zet die periode terug op nul:",
    "s7_li": ["Een account dat nog <strong>leeg</strong> is — geen gebruikersnaam, geen pogingen of antwoorden, geen tokengeschiedenis en een saldo van nul — wordt verwijderd na <strong>60 opeenvolgende dagen</strong> zonder activiteit.",
              "Een account met een <strong>gebruikersnaam of enige wedstrijdgeschiedenis</strong> wordt verwijderd na <strong>365 opeenvolgende dagen</strong> zonder activiteit."],
    "s7_same": "Automatische verwijdering verwijdert precies dezelfde gegevens als punt 4, definitief.",
    "s7_only": "Dit zijn de enige termijnen die op uw gegevens van toepassing zijn. Het zijn uiterste verwijderingstermijnen, geen minimale bewaartermijn: u kunt altijd eerder verwijderen, en niets verplicht ons uw gegevens enige tijd te bewaren.",
}
